version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
